version: "3.9"
services:
  postgres:
    container_name: adventureland_db_container
    image: postgres:15.1-alpine
    ports:
      - '5433:5432'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - adventureland_db_volume:/var/lib/postgresql/data

  flyway:
    container_name: flyway
    image: flyway/flyway:9.10.2-alpine
    depends_on:
      - postgres
    environment:
      FLYWAY_USER: ${POSTGRES_USER}
      FLYWAY_URL: jdbc:postgresql://adventureland_db_container:5432/${POSTGRES_DB}
      FLYWAY_PASSWORD: ${POSTGRES_PASSWORD}
      FLYWAY_DEFAULT_SCHEMA: ${POSTGRES_SCHEMA}
      FLYWAY_CLEAN_DISABLED: "false"
    command:
      -connectRetries=60 migrate
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql

volumes:
  adventureland_db_volume:
