version: "3.9"
services:
  backend:
    container_name: adventureland_backend_container
    build:
      context: .
    image: adventureland_backend_image
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://adventureland_db_container:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    ports:
      - '8081:8080'
    volumes:
      - C:\Users\George\IdeaProjects\RidePairings\src\main\java\com\example\ridepairings:/code

  postgres:
    container_name: adventureland_db_container
    image: postgres:15.1-alpine
    ports:
      - '5433:5432'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - adventureland_db_volume:/var/lib/postgresql/data

volumes:
  adventureland_db_volume:

