CREATE TABLE IF NOT EXISTS ride
(
    id                                BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    external_id                       VARCHAR(255) NOT NULL UNIQUE,
    name                              VARCHAR(255) NOT NULL,
    description                       VARCHAR(255) NOT NULL,
    location                          VARCHAR(255) NOT NULL,
    ride_type                         VARCHAR(255) NOT NULL CHECK (ride_type IN ('Kiddie','Family','Thrill')),
    minimum_height                    INT          NOT NULL,
    maximum_height                    INT,
    maximum_number_of_ride_attendants INT          NOT NULL,
    is_closed                         BOOLEAN          NOT NULL
);